### ISSUE TITLE
Add a Few Aliases and /reply

### ISSUE THREAD

**Issue by Goinging** [MusiJVR/SimpleMsgPlugin#3]
Hi, 
This is small, but I know a lot of people on my server use a lot of different aliases for /msg. The ones I can think of are /m, /w, /whisper and /t that are currently not in this plugin.

/reply and /r are also commands that they are used to, but those may be harder to implement so its not that big a deal.

**Comment by MusiJVR** [comment]
There are plugins that allow you to change the names of existing commands to the names you need. Regarding the `/reply` and `/r` commands, I consider these commands unnecessary, since you can simply send a response message using the `/msg` command. Also, at the moment I have little free time to develop this plugin.

**Comment by Goinging** [comment]
Fair enough, thanks for your help so far and your time.
